### ISSUE TITLE
Silent crash in click.py

### ISSUE THREAD

**Issue by xobs** [AUCOHL/DFFRAM#177]
DFFRAM is causing a silent crash in click.py:

```
Traceback (most recent call last):
  File "/si/bin/lib/python3.7/site-packages/click/core.py", line 1065, in main
    ctx.exit()
  File "/si/bin/lib/python3.7/site-packages/click/core.py", line 687, in exit
    raise Exit(code)
click.exceptions.Exit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/si/bin/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/si/bin/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/si/work/DFFRAM/placeram/__main__.py", line 23, in <module>
    main()
  File "/si/work/DFFRAM/placeram/cli.py", line 317, in main
    cli()
  File "/si/bin/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/si/bin/lib/python3.7/site-packages/click/core.py", line 1083, in main
    sys.exit(e.exit_code)
SystemExit: 0
```

I can't figure out where the actual issue is since there is no line number inside DFFRAM.

**Comment by xobs** [comment]
Note that this is becuase openroad now requires the `-exit` argument, otherwise it gives you a prompt. I was exiting the propmt after the script ran, which caused the crash above.

#178 fixes this issue, so this should be closed when #178 is merged.
